kind = "web"
previewPath = "/"
title = "Invisible Mentors"
version = "1.0.0"
id = "artifacts/invisible-mentors"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
localPort = 21947
name = "web"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/invisible-mentors run dev"

[services.env]
PORT = "21947"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/invisible-mentors", "run", "build"]
publicDir = "artifacts/invisible-mentors/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"
