site_name: "Invisible Mentors"
site_url: https://saisravan909.github.io/invisible-mentors

theme:
  name: material
  palette:
    # This sets the top bar to your Navy Blue
    - primary: custom
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # This allows a Dark Mode (very popular at Linux conferences!)
    - primary: custom
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/saisravan909/invisible-mentors

nav:
  - Home: index.md
  - Onboarding Guide: onboarding.md
